sudo: false
language: cpp

cache:
  apt: true

branches:
  only:
  - master

os:
- linux
- osx

addons:
  apt:
    packages:
    - libboost1.55-all-dev


compiler: clang++

script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Debug ..
- make
- cd ..
- mkdir datasets
- curl -o datasets/set1.mdf https://sdlpublic.blob.core.windows.net/datasets/set1.mdf
- ./bin/test_dataserver -i ./datasets/set1.mdf -b 0 -s 0 -u 1 -a 1 -r 10 -v 2 -x 40 -q 0 -j -1 -o ./datasets/$$$.h -w 0 --internal 0 --index_for_table 1
- git clone https://github.com/ctpo6/dataserver_dump_mdf.git test
- cd test
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DDATASERVER_DIR=.. ..
- make
- ./mdfd -m ../mdf/TestDataserver.mdf --codepage cp1251 2>TestDataserver.txt
- diff -s TestDataserver.txt ../mdf/TestDataserver.txt

