version: '{branch}-{build}'

branches:
  only:
  - master
skip_tags: true
shallow_clone: true
clone_depth: 1


environment:
  matrix:
     - GENERATOR: "Visual Studio 14"
       CONFIG: Debug

os: Visual Studio 2015

install:
- call "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat"

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 14 Win64" ..
- cmake --build .

matrix:
fast_finish: true