version: '{branch}-{build}'

clone_folder: c:\work\dataserver

branches:
  only:
  - master
skip_tags: true
shallow_clone: true
clone_depth: 1

image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

configuration: Debug

install:
- call "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat"

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 14 Win64" ..
- cmake --build . --config Debug
- cd ..
- mkdir datasets
- curl -o datasets/set1.mdf https://sdlpublic.blob.core.windows.net/datasets/set1.mdf
- .\bin\Debug\test_dataserver.exe -i .\datasets\set1.mdf -b 0 -s 0 -u 1 -a 1 -r 10 -v 2 -x 40 -q 0 -j -1 -o .\datasets\$$$.h -w 0 --internal 0 --index_for_table 1

test_script:
- git clone https://github.com/ctpo6/dataserver_dump_mdf.git test
- cd test
- mkdir build
- cd build
- cmake -G "Visual Studio 14 Win64" -DDATASERVER_DIR=c:\work\dataserver ..
- cmake --build . --config Debug
- Debug\mdfd.exe -m c:\work\dataserver\test\mdf\TestDataserver.mdf --codepage cp1251 2>TestDataserver.txt
- fc TestDataserver.txt c:\work\dataserver\test\mdf\TestDataserver.txt
