version: '{branch}-{build}'

clone_folder: c:\work\dataserver

branches:
  only:
  - master
skip_tags: true
shallow_clone: true
clone_depth: 1

image: Visual Studio 2015

configuration: Debug

install:
- call "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat"

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 14 Win64" ..
- cmake --build .

test_script:
- git clone https://github.com/ctpo6/dataserver_ci_test.git test
- cd test
- mkdir build
- cd build
- cmake -G "Visual Studio 14 Win64" -DDATASERVER_DIR=c:\work\dataserver ..
- cmake --build .
- ctest -V -C debug
